apiVersion : apps/v1
kind: Deployment
metadata:
  name: "shoppingcartaks-3129"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "shoppingcartaks-3129"
  template:
    metadata:
      labels:
        app: "shoppingcartaks-3129"
    spec:
      containers:
        - name: "shoppingcartaks-3129"
          image: "shoppingcartreg.azurecr.io/shoppingcartaks"
          ports:
          - containerPort: 80