apiVersion: v1
kind: Service
metadata:
    name: "shoppingcartaks-d075"
    labels:
        app: "shoppingcartaks-d075"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "shoppingcartaks-d075"