on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: shoppingcartreg.azurecr.io
        username: ${{ secrets.acr_shoppingcartreg_username }}
        password: ${{ secrets.acr_shoppingcartreg_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/Job_post" -f  "Job_post/Dockerfile" -t shoppingcartreg.azurecr.io/shoppingcartaks:${{ github.sha }} --label dockerfile-path=Job_post/Dockerfile
        docker push shoppingcartreg.azurecr.io/shoppingcartaks:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_shoppingcartaks_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep shoppingcartaks9dc5 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace shoppingcartaks9dc5`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: shoppingcartaks9dc5
        container-registry-url: shoppingcartreg.azurecr.io
        container-registry-username: ${{ secrets.acr_shoppingcartreg_username }}
        container-registry-password: ${{ secrets.acr_shoppingcartreg_password }}
        secret-name: shoppingcartdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: shoppingcartaks9dc5
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          shoppingcartreg.azurecr.io/shoppingcartaks:${{ github.sha }}
        imagepullsecrets: |
          shoppingcartdockerauth
